### ISSUE TITLE
Document supported InfluxDB versions

### ISSUE THREAD

**Issue by ehamberg** [timescale/outflux#44]
What versions of InfluxDB does this work for? I see that the `SHOW MEASUREMENTS` exists in 0.9¹, but not in earlier versions, so maybe that's the oldest version you support?

It did not work for 0.7 (😬):

    error executing query: SHOW MEASUREMENTS
    error: expected json response, got "text/plain", with status: 404 and response body: "404 page not found\n"

[1] https://docs.influxdata.com/influxdb/v0.9/query_language/schema_exploration/

**Comment by blagojts** [comment]
Thank you for reporting this. We will update our documentation to mention the supported versions.

**Comment by blagojts** [comment]
With #45 we've updated the documentation and added explicit compatibility tests for different InfluxDB versions. 
We can now confirm that we support InfluxDB versions 1.0 and upwards. Versions before 1.0 (0.13 and such) do not provide data type information for the fields of a measurement and the current implementation of Outflux needs to discover the data type before starting with the data transfer. For versions before 0.9 there is no support for any schema discovery whatsoever.
