### ISSUE TITLE
unable to migrate with tags with blanks or dashes

### ISSUE THREAD

**Issue by globetrotterxxl** [timescale/outflux#46]
I get this error: error executing query: SHOW TAG KEYS FROM current load
but running SHOW TAG KEYS FROM "current load" works.

on another database I get this: 
pipe_swap-pages_ext: could not fetch data set definition for measure: swap-pages
could not discover the tags of measurement 'swap-pages'
error fetching tags for measurement 'swap-pages'
error executing query: SHOW TAG KEYS FROM swap-pages

br

**Comment by blagojts** [comment]
Thank you for trying out Outflux. We have confirmed your issue and will open a PR when it's fixed

**Comment by blagojts** [comment]
PR #47 fixes the problem you encountered. As soon as one of my colleagues reviews the code, it will be merged a bugfixed version will be released

**Comment by blagojts** [comment]
We've just released version 0.1.1. Binaries  are available (https://github.com/timescale/outflux/releases) 
The fix for this issue is in and also support for retention policies

**Comment by sgloutnikov** [comment]
Just ran into this, but with a field name containing a dash inside the measurement, not the measurement name itself. Any relation?
