### ISSUE TITLE
outflux fails if pg user not superuser

### ISSUE THREAD

**Issue by ptrcarta** [timescale/outflux#52]
If `outflux migrate` is run with a postgres user which is the owner of the destination database, but not super-user, the following message is output:
```
ERROR: permission denied for relation telemetry_metadata (SQLSTATE 42501)
```
and the procedure is aborted.

#### expected behaviour:
migration should succeed even without super-user privileges, without altering the telemetry table.

**Comment by dianasaur323** [comment]
hmmm @blagojts agree that we should consider adjusting this behavior actually.. or alternatively don't update the telemetry table in a way that requires super-user privileges?

**Comment by blagojts** [comment]
Hi, we published an update today that addresses exactly this. The PR is #57 and has been merged. A new binary release has been made (0.1.2) that contains this change
