### ISSUE TITLE
Entry point to run the source code

### ISSUE THREAD

**Issue by komal-lunkad** [timescale/outflux#68]
Which is the entrypoint file to run the code?
While installing from source code, the documentation says to `dep ensure -v` but then there is no .toml file in the current project.

When I tried to run the _main.go_ file in the **cmd/outflux** folder, I got the below error
`# command-line-arguments
./main.go:6:2: undefined: RootCmd`

When I tried to run the _root.go_ file in the **cmd/outflux** folder, I got the below error
`../../internal/cli/pipe_service.go:6:2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
        /usr/local/go/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
        /home/komal/Documents/work/go_projects/src/github.com/influxdata/influxdb/client/v2 (from $GOPATH)
../../internal/connections/pgx_mock.go:3:8: cannot find package "github.com/jackc/pgx" in any of:
        /usr/local/go/src/github.com/jackc/pgx (from $GOROOT)
        /home/komal/Documents/work/go_projects/src/github.com/jackc/pgx (from $GOPATH)
root.go:7:2: cannot find package "github.com/spf13/cobra" in any of:
        /usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
        /home/komal/Documents/work/go_projects/src/github.com/spf13/cobra (from $GOPATH)
../../internal/cli/flagparsers/connection_args_parser.go:6:2: cannot find package "github.com/spf13/pflag" in any of:
        /usr/local/go/src/github.com/spf13/pflag (from $GOROOT)
        /home/komal/Documents/work/go_projects/src/github.com/spf13/pflag (from $GOPATH)`

**Comment by atanasovskib** [comment]
Hello, sorry for that. We migrated Outflux a few weeks ago to go modules, and didn't update the README. Will issue an update soon with the correct instructions

**Comment by atanasovskib** [comment]
README is updated, try it out
