### ISSUE TITLE
Could not open connection to TimescaleDB server

### ISSUE THREAD

**Issue by BubbleMilkTea** [timescale/outflux#88]
[root@influx outflux]# ./outflux schema-transfer testdb measurement1--input-server=http://localhost:8086--output-conn="dbname=postgres user=postgres"
2021/07/22 16:43:19 Selected input database: testdb
2021/07/22 16:43:19 Overriding PG environment variables for connection with: sslmode=disable
2021/07/22 16:43:19 could not open connections to input and output database
could not open connection to TimescaleDB Server
FATAL: role "root" does not exist (SQLSTATE 28000)
[root@influx outflux]# 

Both influxDB and TimescaleDB are installed on the same server. The "dbname=postgres user=postgres" couldn't be wrong. Why can't connect to outflux with TSDB?

**Comment by JamesGuthrie** [comment]
As this issue is very old, I'm assuming that you either solved this problem or moved on. It looks like the database parameters might not have been correctly passed.
